### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by MattTheCuber** [matcool/skyblock-jacob#6]
Title

**Comment by Bobu5** [comment]
yeah, ig hosting the website is a little bit pain in the ass because of needing to run minecraft client to use chattriggers, 
i hope this unique minecraft client called [MinecraftConsoleClient](https://github.com/ORelio/Minecraft-Console-Client/) will have a chat triggers support, even tho i dont know if they would even implement it, lets just hope they do implement it so we can use it as the data collector, without using much ram and processing power
